# Generated by Django 4.2.5 on 2023-11-17 06:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(blank=True, default=student.models.generate_student_roll_no, max_length=20, null=True, unique=True)),
                ('student_id', models.CharField(blank=True, max_length=64, null=True)),
                ('file_no', models.CharField(blank=True, max_length=64, null=True)),
                ('age_of_student', models.PositiveIntegerField(blank=True, null=True)),
                ('student_name', models.CharField(max_length=256)),
                ('form_b_no', models.CharField(max_length=15, unique=True, validators=[student.models.validate_cnic], verbose_name='Form B #')),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('religion', models.CharField(blank=True, default='Islam', max_length=256, null=True)),
                ('father_name', models.CharField(max_length=256)),
                ('father_cnic', models.CharField(max_length=15, validators=[student.models.validate_cnic])),
                ('father_guardian_occupation', models.CharField(max_length=15, validators=[student.models.validate_cnic])),
                ('mother_name', models.CharField(max_length=256)),
                ('mother_cnic', models.CharField(blank=True, max_length=15, null=True, validators=[student.models.validate_cnic])),
                ('parent_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=256, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=256, null=True)),
                ('date_of_admission', models.DateField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.class')),
            ],
        ),
    ]
